project_id = "oztnbxuxhonoyzzwlhin"

[functions.fix-article]
verify_jwt = false

[functions.generate-article]
verify_jwt = false

[functions.generate-pin-image]
verify_jwt = false

[functions.analyze-recipe]
verify_jwt = false

[functions.send-to-wordpress]
verify_jwt = false
